<a href="https://colab.research.google.com/github/Mathieu-Germain/LogicMojo-AI-ML-April26-Mathieu/blob/main/PandasPractical.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [4]:
import pandas as pd

In [6]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

In [10]:
df = pd.read_csv('/content/drive/MyDrive/MyPracticePandasWitnNulls.csv')
df

    Roll No  Physics  Chemistry  Maths  Computer Science
0         1      9.0       92.0   49.0              85.0
1         2     93.0       61.0   83.0              75.0
2         3     74.0       29.0   61.0              99.0
3         4      8.0       25.0   24.0              68.0
4         5     26.0       13.0    1.0               2.0
..      ...      ...        ...    ...               ...
81       82     12.0       94.0   38.0              77.0
82       83     64.0        5.0   93.0               8.0
83       84     54.0        8.0   32.0              46.0
84       85      NaN       61.0    NaN               NaN
85       86     99.0       97.0   46.0               4.0

[86 rows x 5 columns]

In [11]:
df.head()

   Roll No  Physics  Chemistry  Maths  Computer Science
0        1      9.0       92.0   49.0              85.0
1        2     93.0       61.0   83.0              75.0
2        3     74.0       29.0   61.0              99.0
3        4      8.0       25.0   24.0              68.0
4        5     26.0       13.0    1.0               2.0

In [12]:
df.describe()

         Roll No   Physics  Chemistry      Maths  Computer Science
count  86.000000  80.00000  79.000000  81.000000         77.000000
mean   43.500000  42.98750  47.430380  44.530864         46.623377
std    24.969982  30.98652  27.919152  32.429187         31.471808
min     1.000000   2.00000   1.000000   1.000000          2.000000
25%    22.250000  12.75000  25.000000  12.000000         17.000000
50%    43.500000  39.00000  51.000000  44.000000         45.000000
75%    64.750000  69.00000  65.000000  73.000000         77.000000
max    86.000000  99.00000  97.000000  99.000000         99.000000

In [13]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 86 entries, 0 to 85
Data columns (total 5 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   Roll No           86 non-null     int64
 1   Physics           80 non-null     float64
 2   Chemistry         79 non-null     float64
 3   Maths             81 non-null     float64
 4   Computer Science  77 non-null     float64
dtypes: float64(4), int64(1)
memory usage: 3.5 KB

In [14]:
# check if the dataset content null values

df.isnull()

    Roll No  Physics  Chemistry  Maths  Computer Science
0     False    False      False  False             False
1     False    False      False  False             False
2     False    False      False  False             False
3     False    False      False  False             False
4     False    False      False  False             False
..      ...      ...        ...    ...               ...
81    False    False      False  False             False
82    False    False      False  False             False
83    False    False      False  False             False
84    False     True      False   True              True
85    False    False      False  False             False

[86 rows x 5 columns]

In [15]:
# Null values per columns

df.isnull().sum()

Roll No             0
Physics             6
Chemistry           7
Maths               5
Computer Science    9
dtype: int64

In [16]:
# total number of null values in the dataset

df.isnull().sum().sum()

np.int64(27)

In [17]:
df.shape

(86, 5)

In [18]:
df.columns

Index(['Roll No', 'Physics', 'Chemistry', 'Maths', 'Computer Science'], dtype='object')

In [19]:
#removing the null value
# we can drop those rows. Let create another dataframe
df2 = df.dropna()  # default axis = 0

In [20]:
df2.shape

(68, 5)

In [21]:
df2

    Roll No  Physics  Chemistry  Maths  Computer Science
0         1      9.0       92.0   49.0              85.0
1         2     93.0       61.0   83.0              75.0
2         3     74.0       29.0   61.0              99.0
3         4      8.0       25.0   24.0              68.0
4         5     26.0       13.0    1.0               2.0
..      ...      ...        ...    ...               ...
79       80     97.0       48.0   12.0              37.0
81       82     12.0       94.0   38.0              77.0
82       83     64.0        5.0   93.0               8.0
83       84     54.0        8.0   32.0              46.0
85       86     99.0       97.0   46.0               4.0

[68 rows x 5 columns]

In [21]:
# Drop only the column with NaN values
df3 = df.dropna(axis = 1) # axis = 1 for columns
df3.shape

(86, 1)

In [25]:
# if all values in the row is null then remove that row
df5 = df.dropna(how = 'all')
df5.shape

(86, 5)

In [22]:
# if any row is null then  remove that row
df4 = df.dropna(how = 'any')

In [23]:
df4

    Roll No  Physics  Chemistry  Maths  Computer Science
0         1      9.0       92.0   49.0              85.0
1         2     93.0       61.0   83.0              75.0
2         3     74.0       29.0   61.0              99.0
3         4      8.0       25.0   24.0              68.0
4         5     26.0       13.0    1.0               2.0
..      ...      ...        ...    ...               ...
79       80     97.0       48.0   12.0              37.0
81       82     12.0       94.0   38.0              77.0
82       83     64.0        5.0   93.0               8.0
83       84     54.0        8.0   32.0              46.0
85       86     99.0       97.0   46.0               4.0

[68 rows x 5 columns]

In [28]:
df4.dropna().sum()

Roll No             2907.0
Physics             3088.0
Chemistry           3232.0
Maths               2853.0
Computer Science    3121.0
dtype: float64

In [29]:
df4.isnull().sum()

Roll No             0
Physics             0
Chemistry           0
Maths               0
Computer Science    0
dtype: int64

In [36]:
df.isnull().sum()

Roll No             0
Physics             6
Chemistry           7
Maths               5
Computer Science    9
dtype: int64

In [32]:
# let fill all the null value with 0
df7 = df.fillna(0)

In [33]:
df7.isnull().sum()

Roll No             0
Physics             0
Chemistry           0
Maths               0
Computer Science    0
dtype: int64

In [38]:
# We fill null values in different column with different value: we create a dictionary ie: 'physic':none:{, 'chemistry':'Sick', 'Maths':0

df8=df.fillna({'Physics':'none', 'Chemistry':'Sick', 'Maths':0})
df8

    Roll No Physics Chemistry  Maths  Computer Science
0         1     9.0      92.0   49.0              85.0
1         2    93.0      61.0   83.0              75.0
2         3    74.0      29.0   61.0              99.0
3         4     8.0      25.0   24.0              68.0
4         5    26.0      13.0    1.0               2.0
..      ...     ...       ...    ...               ...
81       82    12.0      94.0   38.0              77.0
82       83    64.0       5.0   93.0               8.0
83       84    54.0       8.0   32.0              46.0
84       85    none      61.0    0.0               NaN
85       86    99.0      97.0   46.0               4.0

[86 rows x 5 columns]

In [41]:
# we can fill the null value with the previous value  method= 'ffill'
df9 = df.fillna(method = 'ffill', axis= 0) # axis = 0 (axis--> =0) is the default value. axis = 1 is column. When x = 1 it fills with he previous column value
df9.head(30)

/tmp/ipykernel_3415/2366034375.py:2: FutureWarning: DataFrame.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  df9 = df.fillna(method = 'ffill')

    Roll No  Physics  Chemistry  Maths  Computer Science
0         1      9.0       92.0   49.0              85.0
1         2     93.0       61.0   83.0              75.0
2         3     74.0       29.0   61.0              99.0
3         4      8.0       25.0   24.0              68.0
4         5     26.0       13.0    1.0               2.0
5         6     53.0       17.0   56.0              26.0
6         7     98.0       43.0   49.0              28.0
7         8     88.0       57.0    3.0              38.0
8         9     18.0       18.0   16.0               8.0
9        10     18.0       38.0   76.0              25.0
10       11     79.0       38.0   19.0              36.0
11       12     46.0       57.0   28.0              69.0
12       13     44.0       33.0   28.0              98.0
13       14     69.0       51.0   24.0              46.0
14       15     16.0       61.0    1.0              98.0
15       16     69.0       62.0   91.0               8.0
16       17     35.0       49.0   97.0              62.0
17       18     86.0        2.0    2.0              36.0
18       19     17.0       78.0   33.0              84.0
19       20     28.0       86.0    8.0              86.0
20       21     28.0       81.0   95.0              97.0
21       22     59.0        5.0   95.0               7.0
22       23     31.0        1.0    3.0              68.0
23       24     74.0       57.0    1.0              61.0
24       25     92.0       82.0   88.0               2.0
25       26     43.0        4.0   36.0              79.0
26       27     98.0       59.0   27.0              78.0
27       28      6.0       38.0   28.0              78.0
28       29     58.0        4.0   89.0              67.0
29       30     31.0       25.0   26.0              37.0

In [47]:
# we can fill the null value with the next value  method= 'bfill'
df11 = df.fillna(method = 'bfill', axis= 0) # axis = 0 (axis--> =0) is the default value. axis = 1 is column. When x = 1 it fills with he previous column value
df11.head(30)

/tmp/ipykernel_3415/2006320552.py:2: FutureWarning: DataFrame.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  df11 = df.fillna(method = 'bfill', axis= 0) # axis = 0 (axis--> =0) is the default value. axis = 1 is column. When x = 1 it fills with he previous column value

    Roll No  Physics  Chemistry  Maths  Computer Science
0         1      9.0       92.0   49.0              85.0
1         2     93.0       61.0   83.0              75.0
2         3     74.0       29.0   61.0              99.0
3         4      8.0       25.0   24.0              68.0
4         5     26.0       13.0    1.0               2.0
5         6     53.0       17.0   56.0              26.0
6         7     98.0       43.0   49.0              28.0
7         8     88.0       57.0    3.0              38.0
8         9     18.0       18.0   16.0               8.0
9        10     79.0       38.0   76.0              25.0
10       11     79.0       57.0   19.0              36.0
11       12     46.0       57.0   28.0              69.0
12       13     44.0       33.0   24.0              98.0
13       14     69.0       51.0   24.0              46.0
14       15     16.0       61.0    1.0              98.0
15       16     69.0       62.0   91.0               8.0
16       17     35.0       49.0   97.0              62.0
17       18     86.0        2.0    2.0              36.0
18       19     17.0       78.0   33.0              84.0
19       20     28.0       86.0    8.0              86.0
20       21     59.0       81.0   95.0              97.0
21       22     59.0        5.0    3.0               7.0
22       23     31.0        1.0    3.0              68.0
23       24     74.0       57.0    1.0              61.0
24       25     92.0       82.0   88.0               2.0
25       26     43.0        4.0   36.0              79.0
26       27     98.0       59.0   27.0              78.0
27       28      6.0       38.0   28.0              67.0
28       29     58.0        4.0   89.0              67.0
29       30     31.0       25.0   26.0              37.0

In [46]:
# we can fill the null value with the mean of the column value
df10 = df['Physics'].fillna(value=df['Physics'].mean())
df10.head(85)

0      9.0000
1     93.0000
2     74.0000
3      8.0000
4     26.0000
       ...
80    42.9875
81    12.0000
82    64.0000
83    54.0000
84    42.9875
Name: Physics, Length: 85, dtype: float64

REPLACE FUNCION

In [49]:
# Let replace 18 with 81 Physics & Chemistry index[8]
df12=df.replace(to_replace=18, value=81)
df12.head(10)

   Roll No  Physics  Chemistry  Maths  Computer Science
0        1      9.0       92.0   49.0              85.0
1        2     93.0       61.0   83.0              75.0
2        3     74.0       29.0   61.0              99.0
3        4      8.0       25.0   24.0              68.0
4        5     26.0       13.0    1.0               2.0
5        6     53.0       17.0   56.0              26.0
6        7     98.0       43.0   49.0              28.0
7        8     88.0       57.0    3.0              38.0
8        9     81.0       81.0   16.0               8.0
9       10      NaN       38.0   76.0              25.0

In [52]:
# We can provide the list of the number we want to replace
df13=df.replace(to_replace=[92,93,94,95,96,97,98,99], value='A')
df13.head(10)

   Roll No Physics Chemistry Maths Computer Science
0        1     9.0         A  49.0             85.0
1        2       A      61.0  83.0             75.0
2        3    74.0      29.0  61.0                A
3        4     8.0      25.0  24.0             68.0
4        5    26.0      13.0   1.0              2.0
5        6    53.0      17.0  56.0             26.0
6        7       A      43.0  49.0             28.0
7        8    88.0      57.0   3.0             38.0
8        9    18.0      18.0  16.0              8.0
9       10     NaN      38.0  76.0             25.0

In [53]:
# Replace respectively with another. this list: [92,93,94,95,96,97,98,99], with: ['A','B','C','D','E','F','G','H'])
df14=df.replace(to_replace=[92,93,94,95,96,97,98,99], value=['A','B','C','D','E','F','G','H'])
df14.head(10)

   Roll No Physics Chemistry Maths Computer Science
0        1     9.0         A  49.0             85.0
1        2       B      61.0  83.0             75.0
2        3    74.0      29.0  61.0                H
3        4     8.0      25.0  24.0             68.0
4        5    26.0      13.0   1.0              2.0
5        6    53.0      17.0  56.0             26.0
6        7       G      43.0  49.0             28.0
7        8    88.0      57.0   3.0             38.0
8        9    18.0      18.0  16.0              8.0
9       10     NaN      38.0  76.0             25.0

In [62]:
# to replace a string caracter with any number or expression, we us 'regex'
df16 = df14.replace('[A-Za-z]', 0, regex=True)
df16.head(10)

/tmp/ipykernel_3415/1644648887.py:2: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df16 = df14.replace('[A-Za-z]', 0, regex=True)

   Roll No  Physics  Chemistry  Maths  Computer Science
0        1      9.0        0.0   49.0              85.0
1        2      0.0       61.0   83.0              75.0
2        3     74.0       29.0   61.0               0.0
3        4      8.0       25.0   24.0              68.0
4        5     26.0       13.0    1.0               2.0
5        6     53.0       17.0   56.0              26.0
6        7      0.0       43.0   49.0              28.0
7        8     88.0       57.0    3.0              38.0
8        9     18.0       18.0   16.0               8.0
9       10      NaN       38.0   76.0              25.0

In [59]:
# YOu can replace value from specific column ie physics only:
df15 = df['Physics'].replace(to_replace=[92,93,94,95,96,97,98,99], value=['A','B','C','D','E','F','G','H'])
df15.head(10)

0     9.0
1       B
2    74.0
3     8.0
4    26.0
5    53.0
6       G
7    88.0
8    18.0
9     NaN
Name: Physics, dtype: object

In [55]:
df.head(30)

    Roll No  Physics  Chemistry  Maths  Computer Science
0         1      9.0       92.0   49.0              85.0
1         2     93.0       61.0   83.0              75.0
2         3     74.0       29.0   61.0              99.0
3         4      8.0       25.0   24.0              68.0
4         5     26.0       13.0    1.0               2.0
5         6     53.0       17.0   56.0              26.0
6         7     98.0       43.0   49.0              28.0
7         8     88.0       57.0    3.0              38.0
8         9     18.0       18.0   16.0               8.0
9        10      NaN       38.0   76.0              25.0
10       11     79.0        NaN   19.0              36.0
11       12     46.0       57.0   28.0              69.0
12       13     44.0       33.0    NaN              98.0
13       14     69.0       51.0   24.0              46.0
14       15     16.0       61.0    1.0              98.0
15       16     69.0       62.0   91.0               8.0
16       17     35.0       49.0   97.0              62.0
17       18     86.0        2.0    2.0              36.0
18       19     17.0       78.0   33.0              84.0
19       20     28.0       86.0    8.0              86.0
20       21      NaN       81.0   95.0              97.0
21       22     59.0        5.0    NaN               7.0
22       23     31.0        1.0    3.0              68.0
23       24     74.0       57.0    1.0              61.0
24       25     92.0       82.0   88.0               2.0
25       26     43.0        4.0   36.0              79.0
26       27     98.0       59.0   27.0              78.0
27       28      6.0       38.0   28.0               NaN
28       29     58.0        4.0   89.0              67.0
29       30     31.0       25.0   26.0              37.0

In [65]:
df

    Roll No  Physics  Chemistry  Maths  Computer Science
0         1      9.0       92.0   49.0              85.0
1         2     93.0       61.0   83.0              75.0
2         3     74.0       29.0   61.0              99.0
3         4      8.0       25.0   24.0              68.0
4         5     26.0       13.0    1.0               2.0
..      ...      ...        ...    ...               ...
81       82     12.0       94.0   38.0              77.0
82       83     64.0        5.0   93.0               8.0
83       84     54.0        8.0   32.0              46.0
84       85      NaN       61.0    NaN               NaN
85       86     99.0       97.0   46.0               4.0

[86 rows x 5 columns]

========== LOC & ILOC ===================

The easiest way to remember the difference is by looking at the letters in their names:

- loc is for label-based indexing (using the names of rows or columns).

- iloc is for integer-based indexing (using the 0-indexed position, just like a standard Python list).

To use the 'Roll No' column as the index, you should use df.set_index('Roll No')

In [71]:
# LOC ## Let change our index to Rll No. Notice that it start a 1 not 0
df = df.set_index('Roll No')
df.head()

         Physics  Chemistry  Maths  Computer Science
Roll No
1            9.0       92.0   49.0              85.0
2           93.0       61.0   83.0              75.0
3           74.0       29.0   61.0              99.0
4            8.0       25.0   24.0              68.0
5           26.0       13.0    1.0               2.0

In [72]:
df.loc[1] # Our index row start at 1 not 0

Physics              9.0
Chemistry           92.0
Maths               49.0
Computer Science    85.0
Name: 1, dtype: float64

In [73]:
df.loc[5]

Physics             26.0
Chemistry           13.0
Maths                1.0
Computer Science     2.0
Name: 5, dtype: float64

In [76]:
# We can provide array of index:
df.loc[[3,5,2]]

         Physics  Chemistry  Maths  Computer Science
Roll No
3           74.0       29.0   61.0              99.0
5           26.0       13.0    1.0               2.0
2           93.0       61.0   83.0              75.0

In [79]:
# to see the physics mark for index 5
df.loc[5, 'Physics']

np.float64(26.0)

**The Big Gotcha: Slicing Behavior ⚠️**

The most common mistake people make comes when slicing multiple rows (using the : operator). They handle the stop value differently:

- loc includes the last item. (It's inclusive).

- iloc excludes the last item. (It behaves exactly like standard Python lists).

In [78]:
# Slicing ==> 1:5. To see the Physics mark from 1 to 5.  includ 5 with iloc it will exclud 5

df.loc[1:5, 'Physics']

Roll No
1     9.0
2    93.0
3    74.0
4     8.0
5    26.0
Name: Physics, dtype: float64

In [82]:
# To see the Physics marks <50
df_50 = df.loc[df['Physics']< 50]
df_50

         Physics  Chemistry  Maths  Computer Science
Roll No
1            9.0       92.0   49.0              85.0
4            8.0       25.0   24.0              68.0
5           26.0       13.0    1.0               2.0
9           18.0       18.0   16.0               8.0
12          46.0       57.0   28.0              69.0
13          44.0       33.0    NaN              98.0
15          16.0       61.0    1.0              98.0
17          35.0       49.0   97.0              62.0
19          17.0       78.0   33.0              84.0
20          28.0       86.0    8.0              86.0
23          31.0        1.0    3.0              68.0
26          43.0        4.0   36.0              79.0
28           6.0       38.0   28.0               NaN
30          31.0       25.0   26.0              37.0
31           4.0        4.0   38.0               5.0
32          11.0       17.0   67.0              86.0
33          27.0       73.0   84.0              32.0
34          22.0        8.0   45.0               5.0
36          22.0        NaN   78.0              87.0
39          39.0        2.0   58.0              38.0
40          22.0       63.0   97.0               NaN
42           4.0       85.0   81.0              63.0
43           7.0       77.0   73.0              95.0
45          39.0       49.0   18.0              45.0
49           2.0        NaN   91.0               NaN
50          44.0        NaN    4.0               NaN
51          33.0       61.0    8.0               7.0
53           4.0       66.0   73.0              41.0
54           5.0        NaN   49.0              28.0
55          46.0       38.0   92.0               9.0
58          28.0        NaN    1.0               NaN
59           4.0       81.0    2.0              83.0
60          28.0       52.0   93.0              82.0
61          13.0       84.0    9.0               5.0
63           9.0       85.0    1.0              46.0
64           2.0       55.0   67.0              11.0
65           6.0       61.0    NaN               6.0
68           7.0       76.0   16.0              34.0
69           9.0       21.0    9.0              44.0
70           7.0       66.0   23.0              23.0
71          44.0       51.0   68.0               6.0
72          18.0       13.0   39.0               7.0
74           6.0       25.0   57.0              54.0
75          27.0        6.0   12.0              77.0
77           8.0       95.0   11.0              89.0
79          34.0       63.0   73.0               NaN
82          12.0       94.0   38.0              77.0

In [83]:
# show only the maths result for student with > 80 in Physics
df.loc[df['Physics']>80, ['Maths']]

         Maths
Roll No
2         83.0
7         49.0
8          3.0
18         2.0
25        88.0
27        27.0
35        79.0
37        58.0
57        99.0
67        69.0
80        12.0
86        46.0

In [85]:
# With iloc to see the first index [0]

df.iloc[0]

Physics              9.0
Chemistry           92.0
Maths               49.0
Computer Science    85.0
Name: 1, dtype: float64

In [87]:
df.iloc[1:5, 0] # 0 here is teh index position of Physics

Roll No
2    93.0
3    74.0
4     8.0
5    26.0
Name: Physics, dtype: float64

In [97]:
# show only the maths result for student with > 80 in Physics
df.loc[df['Physics']>80, ['Maths']]

# show only the maths result for student with > 80 in Physics
# df.loc[df['Physics']>80, ['Maths']]

         Maths
Roll No
2         83.0
7         49.0
8          3.0
18         2.0
25        88.0
27        27.0
35        79.0
37        58.0
57        99.0
67        69.0
80        12.0
86        46.0